### ISSUE TITLE
Create page structure

### ISSUE THREAD

**Issue by garrettdavid1** [DrewDen/soloproject-tier1-ecalendar#3]
We need a section for a calendar and a section for the Event details

**Comment by DrewDen** [comment]
David looking at this calendar I am thinking that the HTML structure would look like a table.

**Comment by garrettdavid1** [comment]
The original structure should just allocate the correct space for each of the two sections: Calendar & Event Details.

**Comment by garrettdavid1** [comment]
Something like 65% width & 100% height for Calendar container & 35% width & 100% height for Event Details container

**Comment by DrewDen** [comment]
Ok, I agree with you on that.  That makes sense I think I was looking ahead on the actual calendar part, but maybe I will use what you send for the container and start there.

**Comment by DrewDen** [comment]
Alright, so I created a new branch and called it structure. I haven't pushed anything up to our repo's master branch, so I don't think I did any harm there.  I can't figure out how to make a pull request if I wanted to do that and have you take a look at it.  The code is a structure for the HTML to give us something to work off of.

**Comment by DrewDen** [comment]
Alright spending a couple of hours on this I understand now how to fix commits made to git if you don't want them there.  I am still a little lost due to that I want to take the code from the structure branch and move it to the master branch.
